# Generated by Django 5.0.14 on 2026-05-01 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('price_per_hour', models.FloatField(default=0)),
                ('pitch_type', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='availabilityslot',
            options={},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('match_invite', 'Match Invite'), ('message', 'Message'), ('reminder', 'Reminder'), ('ai_suggestion', 'AI Suggestion')], max_length=20),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('total_players', models.IntegerField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.ground')),
                ('joined_players', models.ManyToManyField(blank=True, related_name='joined_matches', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_matches', to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.sport')),
            ],
        ),
        migrations.DeleteModel(
            name='MatchInvite',
        ),
    ]
