# Generated by Django 5.0.14 on 2026-10-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground',
            name='maps_place_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ground',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('big', 'Big')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='ground',
            name='source',
            field=models.CharField(default='manual', max_length=30),
        ),
    ]
