# Generated by Django 5.0.14 on 2026-09-30 16:40

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def populate_sport_slugs(apps, schema_editor):
    sport_model = apps.get_model('my_app', 'Sport')
    for sport in sport_model.objects.filter(slug__isnull=True).order_by('id'):
        base_slug = slugify(sport.name)[:60]
        candidate = base_slug
        sequence = 2
        while sport_model.objects.exclude(pk=sport.pk).filter(slug=candidate).exists():
            suffix = f'-{sequence}'
            candidate = f'{base_slug[:60 - len(suffix)]}{suffix}'
            sequence += 1
        sport.slug = candidate
        sport.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_user_account_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert'), ('pro', 'Pro')], default='beginner', max_length=16)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('preferred', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='availability',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='preferred_distance',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='preferred_play_times',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('sports_only', 'Sports only'), ('private', 'Private')], default='public', max_length=16),
        ),
        migrations.AddField(
            model_name='sport',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.RunPython(populate_sport_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='sport',
            name='slug',
            field=models.SlugField(max_length=60, unique=True),
        ),
        migrations.AddConstraint(
            model_name='playerprofile',
            constraint=models.CheckConstraint(check=models.Q(('preferred_distance__gte', 1), ('preferred_distance__lte', 500)), name='profile_preferred_distance_is_valid'),
        ),
        migrations.AddField(
            model_name='usersport',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='my_app.sport'),
        ),
        migrations.AddField(
            model_name='usersport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usersport',
            index=models.Index(fields=['sport', 'skill_level'], name='user_sport_skill_idx'),
        ),
        migrations.AddConstraint(
            model_name='usersport',
            constraint=models.UniqueConstraint(fields=('user', 'sport'), name='unique_user_sport'),
        ),
        migrations.AddConstraint(
            model_name='usersport',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 0), ('rating__lte', 5)), name='user_sport_rating_is_valid'),
        ),
        migrations.AddConstraint(
            model_name='usersport',
            constraint=models.CheckConstraint(check=models.Q(('wins__lte', models.F('matches_played'))), name='user_sport_wins_valid'),
        ),
        migrations.AddConstraint(
            model_name='usersport',
            constraint=models.CheckConstraint(check=models.Q(('losses__lte', models.F('matches_played'))), name='user_sport_losses_valid'),
        ),
        migrations.AddConstraint(
            model_name='usersport',
            constraint=models.CheckConstraint(check=models.Q(('wins__lte', django.db.models.expressions.CombinedExpression(models.F('matches_played'), '-', models.F('losses')))), name='user_sport_results_do_not_exceed_matches'),
        ),
    ]
