# Generated by Django 5.0.14 on 2026-09-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_seed_core_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ground',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='grounds', to='my_app.sport'),
        ),
    ]
