# Generated by Django 5.0.14 on 2026-09-30 17:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_userblock_userblock_unique_user_block_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parking', models.BooleanField(default=False)),
                ('washroom', models.BooleanField(default=False)),
                ('changing_room', models.BooleanField(default=False)),
                ('drinking_water', models.BooleanField(default=False)),
                ('equipment', models.BooleanField(default=False)),
                ('lighting', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('seating', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='venues/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='VenueReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='VenueSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courts', to='my_app.sport')),
            ],
        ),
        migrations.CreateModel(
            name='CourtBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed')], db_index=True, default='confirmed', max_length=16)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='my_app.court')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['city', 'active'], name='venue_city_active_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.CheckConstraint(check=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='venue_latitude_valid'),
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.CheckConstraint(check=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='venue_longitude_valid'),
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 0), ('rating__lte', 5)), name='venue_rating_valid'),
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.CheckConstraint(check=models.Q(('closing_time__gt', models.F('opening_time'))), name='venue_hours_valid'),
        ),
        migrations.AddField(
            model_name='court',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='my_app.venue'),
        ),
        migrations.AddField(
            model_name='venueamenity',
            name='venue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='my_app.venue'),
        ),
        migrations.AddField(
            model_name='venueimage',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='my_app.venue'),
        ),
        migrations.AddField(
            model_name='venuereview',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='my_app.courtbooking'),
        ),
        migrations.AddField(
            model_name='venuereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venuereview',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='my_app.venue'),
        ),
        migrations.AddField(
            model_name='venuesport',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_offerings', to='my_app.sport'),
        ),
        migrations.AddField(
            model_name='venuesport',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_sports', to='my_app.venue'),
        ),
        migrations.AddIndex(
            model_name='courtbooking',
            index=models.Index(fields=['court', 'starts_at', 'status'], name='booking_court_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='courtbooking',
            constraint=models.CheckConstraint(check=models.Q(('ends_at__gt', models.F('starts_at'))), name='booking_time_valid'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['sport', 'active', 'price_per_hour'], name='court_discovery_idx'),
        ),
        migrations.AddConstraint(
            model_name='court',
            constraint=models.UniqueConstraint(fields=('venue', 'name'), name='unique_court_name_per_venue'),
        ),
        migrations.AddConstraint(
            model_name='court',
            constraint=models.CheckConstraint(check=models.Q(('capacity__gt', 0)), name='court_capacity_valid'),
        ),
        migrations.AddConstraint(
            model_name='court',
            constraint=models.CheckConstraint(check=models.Q(('price_per_hour__gte', 0)), name='court_price_valid'),
        ),
        migrations.AddIndex(
            model_name='venuereview',
            index=models.Index(fields=['venue', 'created_at'], name='review_venue_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='venuereview',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_valid'),
        ),
        migrations.AddConstraint(
            model_name='venuesport',
            constraint=models.UniqueConstraint(fields=('venue', 'sport'), name='unique_venue_sport'),
        ),
    ]
