# Generated by Django 5.0.14 on 2026-09-30 17:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_venueamenity_venueimage_venuereview_venuesport_court_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=64),
        ),
        migrations.AlterField(
            model_name='courtbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed')], db_index=True, default='confirmed', max_length=16),
        ),
        migrations.CreateModel(
            name='CourtBlockedPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('type', models.CharField(choices=[('blocked', 'Blocked'), ('maintenance', 'Maintenance')], default='blocked', max_length=16)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_periods', to='my_app.court')),
            ],
            options={
                'indexes': [models.Index(fields=['court', 'starts_at', 'ends_at'], name='court_block_period_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='courtblockedperiod',
            constraint=models.CheckConstraint(check=models.Q(('ends_at__gt', models.F('starts_at'))), name='blocked_period_time_valid'),
        ),
    ]
