# Generated by Django 5.0.14 on 2026-10-05 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_ground_sports_and_size'),
        ('my_app', '0012_venuecancellationpolicy_courtbooking_additional_fees_and_more'),
    ]

    operations = [
    ]
