import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies=[('my_app','0017_events_tournaments')]
 operations=[
 migrations.CreateModel(name='NotificationPreference',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('public_id',models.UUIDField(db_index=True,default=uuid.uuid4,editable=False,unique=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('game_notifications',models.BooleanField(default=True)),('booking_notifications',models.BooleanField(default=True)),('chat_notifications',models.BooleanField(default=True)),('community_notifications',models.BooleanField(default=True)),('event_notifications',models.BooleanField(default=True)),('tournament_notifications',models.BooleanField(default=True)),('marketing_notifications',models.BooleanField(default=False)),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='notification_preferences',to=settings.AUTH_USER_MODEL))]),
 migrations.CreateModel(name='UserDevice',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('public_id',models.UUIDField(db_index=True,default=uuid.uuid4,editable=False,unique=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('device_token',models.CharField(max_length=512,unique=True)),('platform',models.CharField(max_length=10)),('device_name',models.CharField(blank=True,max_length=120)),('is_active',models.BooleanField(db_index=True,default=True)),('last_used_at',models.DateTimeField(auto_now=True)),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='devices',to=settings.AUTH_USER_MODEL))]),
 migrations.AddField(model_name='notification',name='actor',field=models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='acted_notifications',to=settings.AUTH_USER_MODEL)),
 migrations.AddField(model_name='notification',name='read_at',field=models.DateTimeField(blank=True,null=True)),migrations.AddField(model_name='notification',name='deleted_at',field=models.DateTimeField(blank=True,null=True)),migrations.AddField(model_name='notification',name='event_key',field=models.CharField(blank=True,db_index=True,max_length=160)),
 migrations.AddIndex(model_name='notification',index=models.Index(fields=['user','is_read','created_at'],name='notif_user_read_time_idx')),migrations.AddIndex(model_name='notification',index=models.Index(fields=['user','type','created_at'],name='notification_user_type_idx')),migrations.AddIndex(model_name='userdevice',index=models.Index(fields=['user','is_active'],name='device_user_active_idx'))]
