import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies=[('my_app','0018_notifications')]
 operations=[
 migrations.CreateModel(name='PlayerRating',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('public_id',models.UUIDField(db_index=True,default=uuid.uuid4,editable=False,unique=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('rating',models.PositiveSmallIntegerField()),('review',models.TextField(blank=True)),('deleted_at',models.DateTimeField(blank=True,null=True)),('game',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='player_ratings',to='my_app.game')),('player',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='ratings_received',to=settings.AUTH_USER_MODEL)),('reviewer',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='ratings_given',to=settings.AUTH_USER_MODEL))]),
 migrations.CreateModel(name='PlayerSportStatistics',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('public_id',models.UUIDField(db_index=True,default=uuid.uuid4,editable=False,unique=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('statistics',models.JSONField(blank=True,default=dict)),('sport',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='player_statistics',to='my_app.sport')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='sport_statistics',to=settings.AUTH_USER_MODEL))]),
 migrations.AddConstraint(model_name='playerrating',constraint=models.CheckConstraint(check=models.Q(('rating__gte',1),('rating__lte',5)),name='player_rating_range_valid')),migrations.AddConstraint(model_name='playerrating',constraint=models.UniqueConstraint(fields=('reviewer','player','game'),name='unique_player_game_rating')),migrations.AddIndex(model_name='playerrating',index=models.Index(fields=['player','created_at'],name='player_rating_created_idx')),migrations.AddConstraint(model_name='playersportstatistics',constraint=models.UniqueConstraint(fields=('user','sport'),name='unique_player_sport_statistics'))]
