# Generated by Django 5.0.14 on 2026-10-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0022_moderation'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notification_user_read_idx',
        ),
        migrations.RemoveField(
            model_name='ground',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ground',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='ground',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('games', 'Games'), ('wins', 'Wins'), ('events', 'Events'), ('tournaments', 'Tournaments'), ('communities', 'Communities'), ('social', 'Social'), ('ratings', 'Ratings'), ('activity', 'Activity')], max_length=16),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('meetup', 'Meetup'), ('competition', 'Competition'), ('tournament', 'Tournament'), ('workshop', 'Workshop'), ('other', 'Other')], default='meetup', max_length=16),
        ),
        migrations.AlterField(
            model_name='event',
            name='skill_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert'), ('pro', 'Pro')], max_length=16),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('full', 'Full'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=12),
        ),
        migrations.AlterField(
            model_name='event',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('community', 'Community')], db_index=True, default='public', max_length=12),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('waitlisted', 'Waitlisted'), ('cancelled', 'Cancelled'), ('removed', 'Removed')], db_index=True, default='registered', max_length=12),
        ),
        migrations.AlterField(
            model_name='moderationaction',
            name='action',
            field=models.CharField(choices=[('warn', 'Warn'), ('hide', 'Hide'), ('remove', 'Remove'), ('suspend', 'Suspend'), ('ban', 'Ban'), ('restore', 'Restore')], db_index=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='moderationaction',
            name='target_type',
            field=models.CharField(choices=[('user', 'User'), ('player_profile', 'Player profile'), ('game', 'Game'), ('community', 'Community'), ('community_post', 'Community post'), ('community_comment', 'Community comment'), ('message', 'Message'), ('event', 'Event'), ('tournament', 'Tournament'), ('rating', 'Rating'), ('venue_review', 'Venue review')], db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('match_invite', 'Match Invite'), ('message', 'Message'), ('reminder', 'Reminder'), ('ai_suggestion', 'AI Suggestion'), ('moderation_warning', 'Moderation Warning'), ('moderation_outcome', 'Moderation Outcome'), ('report_resolved', 'Report Resolved')], max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('abuse', 'Abuse'), ('inappropriate_content', 'Inappropriate content'), ('fake_profile', 'Fake profile'), ('fraud', 'Fraud'), ('cheating', 'Cheating'), ('other', 'Other')], db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='report',
            name='target_type',
            field=models.CharField(choices=[('user', 'User'), ('player_profile', 'Player profile'), ('game', 'Game'), ('community', 'Community'), ('community_post', 'Community post'), ('community_comment', 'Community comment'), ('message', 'Message'), ('event', 'Event'), ('tournament', 'Tournament'), ('rating', 'Rating'), ('venue_review', 'Venue review')], db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('single_elimination', 'Single elimination'), ('double_elimination', 'Double elimination'), ('round_robin', 'Round robin'), ('league', 'League')], default='single_elimination', max_length=24),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='skill_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert'), ('pro', 'Pro')], max_length=16),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('full', 'Full'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=12),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=12),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('eliminated', 'Eliminated'), ('withdrawn', 'Withdrawn'), ('champion', 'Champion')], default='active', max_length=12),
        ),
        migrations.AlterField(
            model_name='tournamentteammember',
            name='role',
            field=models.CharField(choices=[('captain', 'Captain'), ('player', 'Player')], default='player', max_length=10),
        ),
        migrations.AlterField(
            model_name='tournamentteammember',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('left', 'Left'), ('removed', 'Removed')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='platform',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=10),
        ),
        migrations.AlterField(
            model_name='usermoderation',
            name='action',
            field=models.CharField(choices=[('warn', 'Warn'), ('hide', 'Hide'), ('remove', 'Remove'), ('suspend', 'Suspend'), ('ban', 'Ban'), ('restore', 'Restore')], max_length=12),
        ),
        migrations.AlterField(
            model_name='usermoderation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], db_index=True, default='active', max_length=10),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['sport', 'event_date', 'status'], name='event_sport_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['venue', 'event_date'], name='event_venue_date_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organizer', 'status'], name='event_organizer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['event', 'status', 'joined_at'], name='event_participant_waitlist_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['user', 'status'], name='event_participant_user_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['sport', 'start_date', 'status'], name='tournament_sport_date_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentmatch',
            index=models.Index(fields=['tournament', 'round_number', 'status'], name='tournament_match_round_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('start_time'))), name='event_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('minimum_participants__gt', 0)), name='event_min_positive'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('minimum_participants__lte', models.F('maximum_participants'))), name='event_min_lte_max'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('ends_at__gt', models.F('starts_at'))), name='event_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='tournament_date_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(check=models.Q(('maximum_teams__gt', 1)), name='tournament_max_teams_valid'),
        ),
    ]
